version: '3'

services:
  # ----------------------------------
  #   WORKSPACE
  # ----------------------------------
  perl:
    build:
      context: ./perl
    volumes:
      - ../:/usr/src/local
      - /usr/src/local/docker
      - ./logs:/usr/src/local/api/log
    networks:
      - appnet
    command: >
        bash -c "rm -f api/*.pid && /usr/local/bin/hypnotoad -f api/action.px"
  # ----------------------------------
  #   WEB SERVER
  # ----------------------------------
  nginx:
    build:
      context: ./nginx
    depends_on:
      - perl
    volumes:
      - ../static:/var/www/public
      - ./nginx/logs:/var/www/logs
    networks:
      - appnet
    ports:
      - 80:80

networks:
  appnet:
    driver: bridge