requires 'JSON' => '2.0';
requires 'JSON::XS' => '2.0';

requires 'HTTP::Tiny' => '0.076';
requires 'Path::Tiny' => '0.108';
requires 'Class::Tiny' => '1.0';

requires 'Mojolicious' => '8.0';
requires 'Mojo::Pg' => '4.0';
requires 'Mojo::mysql' => '1.1';
requires 'Mojo::SQLite' => '3.0';

requires 'IO::Socket::SSL' => '2.0';
requires 'Net::DNS::Native' => '0.20';
requires 'Email::Sender' => '1.3';
requires 'Text::CSV_XS' => '1.4';

 
 
